Repository peacefulcraft-network/SwordCraftOnline, pull requests merged in 2020-03, with the labels that each got.

#59 Complete Direction Util Class
  src/net/peacefulcraft/sco/SwordCraftOnline.java
  src/net/peacefulcraft/sco/gamehandle/player/SCOPlayer.java
  src/net/peacefulcraft/sco/swordskills/utilities/DirectionalUtil.java
Labels: enhancement, project

#66 Attribute rework
  src/net/peacefulcraft/sco/SwordCraftOnline.java
  src/net/peacefulcraft/sco/commands/SCOAdmin.java
  src/net/peacefulcraft/sco/gamehandle/listeners/ItemDropOnDeath.java
  src/net/peacefulcraft/sco/gamehandle/player/SCOPlayer.java
  src/net/peacefulcraft/sco/mythicmobs/mobs/ActiveMob.java
  src/net/peacefulcraft/sco/mythicmobs/mobs/MythicMob.java
  src/net/peacefulcraft/sco/swordskills/utilities/IDamage.java
  src/net/peacefulcraft/sco/swordskills/utilities/IDamageModifier.java
  src/net/peacefulcraft/sco/swordskills/utilities/Modifier.java
Labels: enhancement

#75 Mythic mob
  src/net/peacefulcraft/sco/SwordCraftOnline.java
  src/net/peacefulcraft/sco/commands/SCOAdmin.java
  src/net/peacefulcraft/sco/mythicmobs/listeners/MobOptions.java
  src/net/peacefulcraft/sco/mythicmobs/listeners/MobSpawnHandler.java
  src/net/peacefulcraft/sco/mythicmobs/listeners/MobTarget.java
  src/net/peacefulcraft/sco/mythicmobs/listeners/MythicMobDeathEvent.java
  src/net/peacefulcraft/sco/mythicmobs/mobs/MobManager.java
  src/net/peacefulcraft/sco/mythicmobs/mobs/MythicMob.java
Labels: enhancement

#76 Updating merchant class with new mythicmob bug fixes
  src/net/peacefulcraft/sco/SwordCraftOnline.java
  src/net/peacefulcraft/sco/commands/SCOAdmin.java
  src/net/peacefulcraft/sco/mythicmobs/listeners/MobOptions.java
  src/net/peacefulcraft/sco/mythicmobs/listeners/MobSpawnHandler.java
  src/net/peacefulcraft/sco/mythicmobs/listeners/MobTarget.java
  src/net/peacefulcraft/sco/mythicmobs/listeners/MythicMobDeathEvent.java
  src/net/peacefulcraft/sco/mythicmobs/mobs/MobManager.java
  src/net/peacefulcraft/sco/mythicmobs/mobs/MythicMob.java
Labels: code cleanup, enhancement

#78 Sword Skills V3.1
  src/net/peacefulcraft/log/SwordSkill.java
  src/net/peacefulcraft/sco/SwordCraftOnline.java
  src/net/peacefulcraft/sco/commands/SCOAdmin.java
  src/net/peacefulcraft/sco/gamehandle/GameManager.java
  src/net/peacefulcraft/sco/items/CriticalStrikeItem.java
  src/net/peacefulcraft/sco/items/SerratedBladeItem.java
  src/net/peacefulcraft/sco/storage/PlayerDataManager.java
  src/net/peacefulcraft/sco/swordskills/CriticalStrikeSkill.java
  src/net/peacefulcraft/sco/swordskills/SerratedBladeSkill.java
  src/net/peacefulcraft/sco/swordskills/SwordSkill.java
  src/net/peacefulcraft/sco/swordskills/SwordSkillComboType.java
  src/net/peacefulcraft/sco/swordskills/SwordSkillManager.java
  src/net/peacefulcraft/sco/swordskills/SwordSkillTest.java
  src/net/peacefulcraft/sco/swordskills/SwordSkillType.java
  src/net/peacefulcraft/sco/swordskills/listeners/AbilityClickListener.java
  src/net/peacefulcraft/sco/swordskills/listeners/AbilityEntityDamageEntityListener.java
  src/net/peacefulcraft/sco/swordskills/modules/BasicCombo.java
  src/net/peacefulcraft/sco/swordskills/modules/SwordSkillModule.java
  src/net/peacefulcraft/sco/swordskills/modules/TimedCombo.java
  src/net/peacefulcraft/sco/swordskills/modules/TimedCooldown.java
Labels: project

#82 Add ability loops for AsyncChat, Teleport, PlayerDeath, Move, and Respawn
  src/net/peacefulcraft/sco/SwordCraftOnline.java
  src/net/peacefulcraft/sco/swordskills/SwordSkillType.java
  src/net/peacefulcraft/sco/swordskills/listeners/AbilityAsyncPlayerChatListener.java
  src/net/peacefulcraft/sco/swordskills/listeners/AbilityEntityTeleportListener.java
  src/net/peacefulcraft/sco/swordskills/listeners/AbilityPlayerDeathListener.java
  src/net/peacefulcraft/sco/swordskills/listeners/AbilityPlayerMoveListener.java
  src/net/peacefulcraft/sco/swordskills/listeners/AbilityPlayerRespawnListener.java
Labels: enhancement, project
